spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/movie_ex
    username: root
    password: 1234

  batch:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

kobis:
  baseUrl: http://kobis.or.kr/kobisopenapi/webservice/rest
  serviceKey: 97171a56bbee4c2c5a0a42022af67e96


server:
  port: ${PORT:8080}